// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// CAN ID
#ifndef CONF_CONTROLLER_ID
#define CONF_CONTROLLER_ID 99
#endif

// CAN Baud Rate
#ifndef CONF_CAN_BAUD_RATE
#define CONF_CAN_BAUD_RATE 2
#endif

// CAN Status Rate
#ifndef CONF_CAN_STATUS_RATE_HZ
#define CONF_CAN_STATUS_RATE_HZ 10
#endif

// Number of Cells
#ifndef CONF_CELL_NUM
#define CONF_CELL_NUM 20
#endif

// Balancing Mode
#ifndef CONF_BALANCE_MODE
#define CONF_BALANCE_MODE 2
#endif

// Charge Minimum Voltage
#ifndef CONF_CHARGE_MIN
#define CONF_CHARGE_MIN 2.3
#endif

// Charge Start Voltage
#ifndef CONF_CHARGE_START
#define CONF_CHARGE_START 3
#endif

// Charge End Voltage
#ifndef CONF_CHARGE_END
#define CONF_CHARGE_END 4.2
#endif

// Discharge Minimum Voltage
#ifndef CONF_DISCHARGE_MIN
#define CONF_DISCHARGE_MIN 2.7
#endif

// Balance Minimum Voltage
#ifndef CONF_BALANCE_MIN
#define CONF_BALANCE_MIN 3.82
#endif

// Balance Starting Voltage
#ifndef CONF_BALANCE_START
#define CONF_BALANCE_START 0.01
#endif

// Balance End Voltage
#ifndef CONF_BALANCE_END
#define CONF_BALANCE_END 0.005
#endif

// Balance High Threshold Voltage (Delta)
#ifndef CONF_BALANCE_HIGH_THRESHOLD_DELTA
#define CONF_BALANCE_HIGH_THRESHOLD_DELTA 0.001
#endif

// Minimum Temperature (Battery)
#ifndef CONF_T_MIN
#define CONF_T_MIN -20
#endif

// Low Threshold Temperature (Battery)
#ifndef CONF_T_LOW_THRESHOLD
#define CONF_T_LOW_THRESHOLD -15
#endif

// Charge Minimum Temperature (Battery)
#ifndef CONF_T_CHARGE_MIN
#define CONF_T_CHARGE_MIN 0
#endif

// Charge Low Threshold Temperature (Battery)
#ifndef CONF_T_CHARGE_LOW_THRESHOLD
#define CONF_T_CHARGE_LOW_THRESHOLD 5
#endif

// Charge Maximum Temperature (Battery)
#ifndef CONF_T_CHARGE_MAX
#define CONF_T_CHARGE_MAX 55
#endif

// Charge High Threshold Temperature (Battery)
#ifndef CONF_T_CHARGE_HIGH_THRESHOLD
#define CONF_T_CHARGE_HIGH_THRESHOLD 50
#endif

// Charge Maximum Temperature (BMS)
#ifndef CONF_T_BMS_CHARGE_MAX
#define CONF_T_BMS_CHARGE_MAX 65
#endif

// Charge High Threshold Temperature (BMS)
#ifndef CONF_T_BMS_CHARGE_HIGH_THRESHOLD
#define CONF_T_BMS_CHARGE_HIGH_THRESHOLD 60
#endif

// Minimum Charge Current
#ifndef CONF_MIN_CHARGE_CURRENT
#define CONF_MIN_CHARGE_CURRENT 1
#endif

// Maximum Charge Current
#ifndef CONF_MAX_CHARGE_CURRENT
#define CONF_MAX_CHARGE_CURRENT 20
#endif

// Maximum Discharge Current
#ifndef CONF_MAX_DISCHARGE_CURRENT
#define CONF_MAX_DISCHARGE_CURRENT 110
#endif

// Balance Maximum Current
#ifndef CONF_BALANCE_MAX_CURRENT
#define CONF_BALANCE_MAX_CURRENT 3
#endif

// Short-Circuit Detection Voltage
#ifndef CONF_SHORT_CIRCUIT_DETECT_VOLTAGE
#define CONF_SHORT_CIRCUIT_DETECT_VOLTAGE 13
#endif

// High Voltage Delay
#ifndef CONF_OVERVOLTAGE_DELAY
#define CONF_OVERVOLTAGE_DELAY 1
#endif

// Low Voltage Delay
#ifndef CONF_UNDERVOLTAGE_DELAY
#define CONF_UNDERVOLTAGE_DELAY 15
#endif

// High Charge Current Reset Delay
#ifndef CONF_CHARGE_OVERCURRENT_DELAY
#define CONF_CHARGE_OVERCURRENT_DELAY 10
#endif

// High Discharge Current Delay
#ifndef CONF_DISCHARGE_OVERCURRENT_DELAY
#define CONF_DISCHARGE_OVERCURRENT_DELAY 1
#endif

// Short-Circuit Detection Time
#ifndef CONF_SHORT_CIRCUIT_DETECT_TIME
#define CONF_SHORT_CIRCUIT_DETECT_TIME 255
#endif

// High Temperature Delay
#ifndef CONF_OVERTEMPERATURE_DELAY
#define CONF_OVERTEMPERATURE_DELAY 1
#endif

// Battery Charge Curve [100%]
#ifndef CONF_SOC_CURVE_100
#define CONF_SOC_CURVE_100 4.2
#endif

// Battery Charge Curve [90%]
#ifndef CONF_SOC_CURVE_90
#define CONF_SOC_CURVE_90 4.075
#endif

// Battery Charge Curve [80%]
#ifndef CONF_SOC_CURVE_80
#define CONF_SOC_CURVE_80 4.04
#endif

// Battery Charge Curve [70%]
#ifndef CONF_SOC_CURVE_70
#define CONF_SOC_CURVE_70 3.9
#endif

// Battery Charge Curve [60%]
#ifndef CONF_SOC_CURVE_60
#define CONF_SOC_CURVE_60 3.82
#endif

// Battery Charge Curve [50%]
#ifndef CONF_SOC_CURVE_50
#define CONF_SOC_CURVE_50 3.735
#endif

// Battery Charge Curve [40%]
#ifndef CONF_SOC_CURVE_40
#define CONF_SOC_CURVE_40 3.64
#endif

// Battery Charge Curve [30%]
#ifndef CONF_SOC_CURVE_30
#define CONF_SOC_CURVE_30 3.52
#endif

// Battery Charge Curve [20%]
#ifndef CONF_SOC_CURVE_20
#define CONF_SOC_CURVE_20 3.375
#endif

// Battery Charge Curve [10%]
#ifndef CONF_SOC_CURVE_10
#define CONF_SOC_CURVE_10 3.16
#endif

// Battery Charge Curve [0%]
#ifndef CONF_SOC_CURVE_0
#define CONF_SOC_CURVE_0 3
#endif

// Cell Voltage Calibration Factor P1
#ifndef CONF_CELL_VOLTAGE_CALI_P1
#define CONF_CELL_VOLTAGE_CALI_P1 3.5e-07
#endif

// Cell Voltage Calibration Factor P2
#ifndef CONF_CELL_VOLTAGE_CALI_P2
#define CONF_CELL_VOLTAGE_CALI_P2 -1.2e-07
#endif

// Cell Voltage Smoothing Factor K
#ifndef CONF_CELL_VOLTAGE_K
#define CONF_CELL_VOLTAGE_K 0.5
#endif

// Cell Voltage Sag Compensation Table [C1]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_0
#define CONF_CELL_VOLTAGE_SAG_COMP_0 12.51
#endif

// Cell Voltage Sag Compensation Table [C2]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_1
#define CONF_CELL_VOLTAGE_SAG_COMP_1 6.813
#endif

// Cell Voltage Sag Compensation Table [C3]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_2
#define CONF_CELL_VOLTAGE_SAG_COMP_2 6.813
#endif

// Cell Voltage Sag Compensation Table [C4]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_3
#define CONF_CELL_VOLTAGE_SAG_COMP_3 6.813
#endif

// Cell Voltage Sag Compensation Table [C5]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_4
#define CONF_CELL_VOLTAGE_SAG_COMP_4 6.813
#endif

// Cell Voltage Sag Compensation Table [C6]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_5
#define CONF_CELL_VOLTAGE_SAG_COMP_5 6.813
#endif

// Cell Voltage Sag Compensation Table [C7]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_6
#define CONF_CELL_VOLTAGE_SAG_COMP_6 6.813
#endif

// Cell Voltage Sag Compensation Table [C8]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_7
#define CONF_CELL_VOLTAGE_SAG_COMP_7 6.813
#endif

// Cell Voltage Sag Compensation Table [C9]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_8
#define CONF_CELL_VOLTAGE_SAG_COMP_8 6.813
#endif

// Cell Voltage Sag Compensation Table [C10]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_9
#define CONF_CELL_VOLTAGE_SAG_COMP_9 6.813
#endif

// Cell Voltage Sag Compensation Table [C11]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_10
#define CONF_CELL_VOLTAGE_SAG_COMP_10 6.813
#endif

// Cell Voltage Sag Compensation Table [C12]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_11
#define CONF_CELL_VOLTAGE_SAG_COMP_11 6.813
#endif

// Cell Voltage Sag Compensation Table [C13]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_12
#define CONF_CELL_VOLTAGE_SAG_COMP_12 6.813
#endif

// Cell Voltage Sag Compensation Table [C14]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_13
#define CONF_CELL_VOLTAGE_SAG_COMP_13 6.813
#endif

// Cell Voltage Sag Compensation Table [C15]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_14
#define CONF_CELL_VOLTAGE_SAG_COMP_14 6.813
#endif

// Cell Voltage Sag Compensation Table [C16]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_15
#define CONF_CELL_VOLTAGE_SAG_COMP_15 6.813
#endif

// Cell Voltage Sag Compensation Table [C17]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_16
#define CONF_CELL_VOLTAGE_SAG_COMP_16 6.813
#endif

// Cell Voltage Sag Compensation Table [C18]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_17
#define CONF_CELL_VOLTAGE_SAG_COMP_17 13.23
#endif

// Cell Voltage Sag Compensation Table [C19]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_18
#define CONF_CELL_VOLTAGE_SAG_COMP_18 6.813
#endif

// Cell Voltage Sag Compensation Table [C20]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_19
#define CONF_CELL_VOLTAGE_SAG_COMP_19 6.813
#endif

// Cell Voltage Sag Compensation Table [C21]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_20
#define CONF_CELL_VOLTAGE_SAG_COMP_20 0
#endif

// Cell Voltage Sag Compensation Table [C22]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_21
#define CONF_CELL_VOLTAGE_SAG_COMP_21 0
#endif

// Cell Voltage Sag Compensation Table [C23]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_22
#define CONF_CELL_VOLTAGE_SAG_COMP_22 0
#endif

// Cell Voltage Sag Compensation Table [C24]
#ifndef CONF_CELL_VOLTAGE_SAG_COMP_23
#define CONF_CELL_VOLTAGE_SAG_COMP_23 0
#endif

// CONF_DEFAULT_H_
#endif

