// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "confparser.h"

int32_t confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);

	buffer[ind++] = (uint8_t)conf->controller_id;
	buffer[ind++] = conf->can_baud_rate;
	buffer_append_uint32(buffer, conf->can_status_rate_hz, &ind);
	buffer_append_int16(buffer, conf->cell_num, &ind);
	buffer[ind++] = conf->balance_mode;
	buffer_append_float32_auto(buffer, conf->vc_charge_min, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_start, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_end, &ind);
	buffer_append_float32_auto(buffer, conf->vc_discharge_min, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_min, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_start, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_end, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_high_threshold_delta, &ind);
	buffer_append_float16(buffer, conf->t_min, 10, &ind);
	buffer_append_float16(buffer, conf->t_low_threshold, 10, &ind);
	buffer_append_float16(buffer, conf->t_charge_min, 10, &ind);
	buffer_append_float16(buffer, conf->t_charge_low_threshold, 10, &ind);
	buffer_append_float16(buffer, conf->t_charge_max, 10, &ind);
	buffer_append_float16(buffer, conf->t_charge_high_threshold, 10, &ind);
	buffer_append_float16(buffer, conf->t_bms_charge_max, 10, &ind);
	buffer_append_float16(buffer, conf->t_bms_charge_high_threshold, 10, &ind);
	buffer_append_float32_auto(buffer, conf->min_charge_current, &ind);
	buffer_append_float32_auto(buffer, conf->max_charge_current, &ind);
	buffer_append_float32_auto(buffer, conf->max_discharge_current, &ind);
	buffer_append_float32_auto(buffer, conf->balance_max_current, &ind);
	buffer_append_float32_auto(buffer, conf->short_circuit_detection_voltage, &ind);
	buffer_append_float32_auto(buffer, conf->overvoltage_delay, &ind);
	buffer_append_float32_auto(buffer, conf->undervoltage_delay, &ind);
	buffer_append_float32_auto(buffer, conf->charge_overcurrent_reset_delay, &ind);
	buffer_append_float32_auto(buffer, conf->discharge_overcurrent_delay, &ind);
	buffer_append_float32_auto(buffer, conf->short_circuit_detection_time, &ind);
	buffer_append_float32_auto(buffer, conf->overtemperature_delay, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_100, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_90, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_80, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_70, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_60, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_50, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_40, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_30, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_20, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_10, &ind);
	buffer_append_float32_auto(buffer, conf->vc_soc_curve_0, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_cali_p1, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_cali_p2, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_k, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_0, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_1, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_2, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_3, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_4, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_5, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_6, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_7, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_8, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_9, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_10, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_11, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_12, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_13, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_14, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_15, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_16, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_17, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_18, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_19, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_20, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_21, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_22, &ind);
	buffer_append_float32_auto(buffer, conf->cell_voltage_sag_comp_23, &ind);

	return ind;
}

bool confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	conf->controller_id = buffer[ind++];
	conf->can_baud_rate = buffer[ind++];
	conf->can_status_rate_hz = buffer_get_uint32(buffer, &ind);
	conf->cell_num = buffer_get_int16(buffer, &ind);
	conf->balance_mode = buffer[ind++];
	conf->vc_charge_min = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_start = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_end = buffer_get_float32_auto(buffer, &ind);
	conf->vc_discharge_min = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_min = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_start = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_end = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_high_threshold_delta = buffer_get_float32_auto(buffer, &ind);
	conf->t_min = buffer_get_float16(buffer, 10, &ind);
	conf->t_low_threshold = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_min = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_low_threshold = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_max = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_high_threshold = buffer_get_float16(buffer, 10, &ind);
	conf->t_bms_charge_max = buffer_get_float16(buffer, 10, &ind);
	conf->t_bms_charge_high_threshold = buffer_get_float16(buffer, 10, &ind);
	conf->min_charge_current = buffer_get_float32_auto(buffer, &ind);
	conf->max_charge_current = buffer_get_float32_auto(buffer, &ind);
	conf->max_discharge_current = buffer_get_float32_auto(buffer, &ind);
	conf->balance_max_current = buffer_get_float32_auto(buffer, &ind);
	conf->short_circuit_detection_voltage = buffer_get_float32_auto(buffer, &ind);
	conf->overvoltage_delay = buffer_get_float32_auto(buffer, &ind);
	conf->undervoltage_delay = buffer_get_float32_auto(buffer, &ind);
	conf->charge_overcurrent_reset_delay = buffer_get_float32_auto(buffer, &ind);
	conf->discharge_overcurrent_delay = buffer_get_float32_auto(buffer, &ind);
	conf->short_circuit_detection_time = buffer_get_float32_auto(buffer, &ind);
	conf->overtemperature_delay = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_100 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_90 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_80 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_70 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_60 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_50 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_40 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_30 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_20 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_10 = buffer_get_float32_auto(buffer, &ind);
	conf->vc_soc_curve_0 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_cali_p1 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_cali_p2 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_k = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_0 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_1 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_2 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_3 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_4 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_5 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_6 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_7 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_8 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_9 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_10 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_11 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_12 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_13 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_14 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_15 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_16 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_17 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_18 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_19 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_20 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_21 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_22 = buffer_get_float32_auto(buffer, &ind);
	conf->cell_voltage_sag_comp_23 = buffer_get_float32_auto(buffer, &ind);

	return true;
}

void confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = HW_DEFAULT_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->can_status_rate_hz = CONF_CAN_STATUS_RATE_HZ;
	conf->cell_num = CONF_CELL_NUM;
	conf->balance_mode = CONF_BALANCE_MODE;
	conf->vc_charge_min = CONF_CHARGE_MIN;
	conf->vc_charge_start = CONF_CHARGE_START;
	conf->vc_charge_end = CONF_CHARGE_END;
	conf->vc_discharge_min = CONF_DISCHARGE_MIN;
	conf->vc_balance_min = CONF_BALANCE_MIN;
	conf->vc_balance_start = CONF_BALANCE_START;
	conf->vc_balance_end = CONF_BALANCE_END;
	conf->vc_balance_high_threshold_delta = CONF_BALANCE_HIGH_THRESHOLD_DELTA;
	conf->t_min = CONF_T_MIN;
	conf->t_low_threshold = CONF_T_LOW_THRESHOLD;
	conf->t_charge_min = CONF_T_CHARGE_MIN;
	conf->t_charge_low_threshold = CONF_T_CHARGE_LOW_THRESHOLD;
	conf->t_charge_max = CONF_T_CHARGE_MAX;
	conf->t_charge_high_threshold = CONF_T_CHARGE_HIGH_THRESHOLD;
	conf->t_bms_charge_max = CONF_T_BMS_CHARGE_MAX;
	conf->t_bms_charge_high_threshold = CONF_T_BMS_CHARGE_HIGH_THRESHOLD;
	conf->min_charge_current = CONF_MIN_CHARGE_CURRENT;
	conf->max_charge_current = CONF_MAX_CHARGE_CURRENT;
	conf->max_discharge_current = CONF_MAX_DISCHARGE_CURRENT;
	conf->balance_max_current = CONF_BALANCE_MAX_CURRENT;
	conf->short_circuit_detection_voltage = CONF_SHORT_CIRCUIT_DETECT_VOLTAGE;
	conf->overvoltage_delay = CONF_OVERVOLTAGE_DELAY;
	conf->undervoltage_delay = CONF_UNDERVOLTAGE_DELAY;
	conf->charge_overcurrent_reset_delay = CONF_CHARGE_OVERCURRENT_DELAY;
	conf->discharge_overcurrent_delay = CONF_DISCHARGE_OVERCURRENT_DELAY;
	conf->short_circuit_detection_time = CONF_SHORT_CIRCUIT_DETECT_TIME;
	conf->overtemperature_delay = CONF_OVERTEMPERATURE_DELAY;
	conf->vc_soc_curve_100 = CONF_SOC_CURVE_100;
	conf->vc_soc_curve_90 = CONF_SOC_CURVE_90;
	conf->vc_soc_curve_80 = CONF_SOC_CURVE_80;
	conf->vc_soc_curve_70 = CONF_SOC_CURVE_70;
	conf->vc_soc_curve_60 = CONF_SOC_CURVE_60;
	conf->vc_soc_curve_50 = CONF_SOC_CURVE_50;
	conf->vc_soc_curve_40 = CONF_SOC_CURVE_40;
	conf->vc_soc_curve_30 = CONF_SOC_CURVE_30;
	conf->vc_soc_curve_20 = CONF_SOC_CURVE_20;
	conf->vc_soc_curve_10 = CONF_SOC_CURVE_10;
	conf->vc_soc_curve_0 = CONF_SOC_CURVE_0;
	conf->cell_voltage_cali_p1 = CONF_CELL_VOLTAGE_CALI_P1;
	conf->cell_voltage_cali_p2 = CONF_CELL_VOLTAGE_CALI_P2;
	conf->cell_voltage_k = CONF_CELL_VOLTAGE_K;
	conf->cell_voltage_sag_comp_0 = CONF_CELL_VOLTAGE_SAG_COMP_0;
	conf->cell_voltage_sag_comp_1 = CONF_CELL_VOLTAGE_SAG_COMP_1;
	conf->cell_voltage_sag_comp_2 = CONF_CELL_VOLTAGE_SAG_COMP_2;
	conf->cell_voltage_sag_comp_3 = CONF_CELL_VOLTAGE_SAG_COMP_3;
	conf->cell_voltage_sag_comp_4 = CONF_CELL_VOLTAGE_SAG_COMP_4;
	conf->cell_voltage_sag_comp_5 = CONF_CELL_VOLTAGE_SAG_COMP_5;
	conf->cell_voltage_sag_comp_6 = CONF_CELL_VOLTAGE_SAG_COMP_6;
	conf->cell_voltage_sag_comp_7 = CONF_CELL_VOLTAGE_SAG_COMP_7;
	conf->cell_voltage_sag_comp_8 = CONF_CELL_VOLTAGE_SAG_COMP_8;
	conf->cell_voltage_sag_comp_9 = CONF_CELL_VOLTAGE_SAG_COMP_9;
	conf->cell_voltage_sag_comp_10 = CONF_CELL_VOLTAGE_SAG_COMP_10;
	conf->cell_voltage_sag_comp_11 = CONF_CELL_VOLTAGE_SAG_COMP_11;
	conf->cell_voltage_sag_comp_12 = CONF_CELL_VOLTAGE_SAG_COMP_12;
	conf->cell_voltage_sag_comp_13 = CONF_CELL_VOLTAGE_SAG_COMP_13;
	conf->cell_voltage_sag_comp_14 = CONF_CELL_VOLTAGE_SAG_COMP_14;
	conf->cell_voltage_sag_comp_15 = CONF_CELL_VOLTAGE_SAG_COMP_15;
	conf->cell_voltage_sag_comp_16 = CONF_CELL_VOLTAGE_SAG_COMP_16;
	conf->cell_voltage_sag_comp_17 = CONF_CELL_VOLTAGE_SAG_COMP_17;
	conf->cell_voltage_sag_comp_18 = CONF_CELL_VOLTAGE_SAG_COMP_18;
	conf->cell_voltage_sag_comp_19 = CONF_CELL_VOLTAGE_SAG_COMP_19;
	conf->cell_voltage_sag_comp_20 = CONF_CELL_VOLTAGE_SAG_COMP_20;
	conf->cell_voltage_sag_comp_21 = CONF_CELL_VOLTAGE_SAG_COMP_21;
	conf->cell_voltage_sag_comp_22 = CONF_CELL_VOLTAGE_SAG_COMP_22;
	conf->cell_voltage_sag_comp_23 = CONF_CELL_VOLTAGE_SAG_COMP_23;
}

